package com.model;

/**
 * TShoucang generated by MyEclipse Persistence Tools
 */

public class TShoucang implements java.io.Serializable
{

	private Integer id;
	private Integer bookId;
	private String shijian;
	private Integer userId;
	
	private TBook book;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getBookId() {
		return bookId;
	}

	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	public String getShijian() {
		return shijian;
	}

	public void setShijian(String shijian) {
		this.shijian = shijian;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public TBook getBook() {
		return book;
	}

	public void setBook(TBook book) {
		this.book = book;
	}

}